namespace ControllingAndManagingApp.Gcode
{
    public class GCodeInstructions
    {
        public enum GCommands
        {
            RapidLinearMove,
            LinearMove,
            ClockwiseArcMove,
            CounterClockwiseArcMove,
            RetractFilamentAccordingToSettings = 10,
            RetractRecoverFilamentAccordingToSettings,
            CleanTheNozzle,
            MeshValidationPattern = 26,
            ParkToolHead,
            HomeAllAxes,
            AutoBedLeveling,
            SingleZProbe,
            SaveCurrentPossition = 60,
            ReturnToSavedPosition,
            CancelTheBedLevelingProcedure = 80,
            AbsolutePositioning = 90,
            RelativePositioning,
            SetPositions,

        }
        public enum MCommands
        {
            EndOfProgram = 2,
            DisableSteppers = 18,
            ListSdCard = 20,
            InitSdCadr,
            ReleaseSdCard,
            SelectSdFile,
            StartOrResumeSdPrint,
            PauseSdPrint,
            SetSdPosition,
            ReportSdPrintStatus,
            StartSdWrite,
            StopSdWrite,
            DeleteSdFile,
            PrintTime,
            SelectAndStart,
            ProbeRepeatabilityTest = 48,
            SetPrintProgress = 73,
            StartPrintJobTimer = 75,
            PausePrintJobTimer,
            StopPrintJobTimer,
            PrintJobStats,
            PowerOn = 80,
            PowerOff,
            EAbsolute,
            ERelative,
            SetAxisStepsPerUnit = 92,
            FreeMemory = 100,
            SetHotendTemperature = 104,
            ReportTemperatures,
            SetFanSpeed,
            FanOff,
            BreakAndContinue,
            WaitForHotendTemperature,
            FullShutDown = 112,
            HostKeepAlive,
            GetCurrentPosition,
            FirmwareInfo,
            SetLCDStatus = 117,
            SerialPrint,
            EndstopStates,
            EnableEndstops,
            DisableEndstops,
            TMCDebug,
            ParkHead = 125,
            SetBedTemperature = 140,
            SetChamberTemperature,
            SetMaterialPreset = 145,
            SetTemperatureUnits = 149,
            SetRGBColors,
            PositionAutoReport = 154,
            TemperatureAutoReport,
            WaitForBedTemperature = 190,
            WaitForChamberTemperature,
            WaitForProbeTemperature,
            SetFilamentDiameter = 200,
            PrintTravelMoveLimits,
            SetMaxFeedrates = 203,
            SetStartingAcceleration,
            SetAdvancedSettings,
            SetHomeOffsets,
            SetFirmwareRetraction,
            FirmwareRecover,
            SetAutoRetract,
            SetHotendOffset = 218,
            SetFeedratePercentage = 220,
            SetFlowPercentage,
            TriggerCamera = 240,
            I2CSend = 260,
            I2CRequest,
            BabyStep = 290,
            PlayTone = 300,
            SetHotendPID,
            ColdExtrude,
            PIDAutoTune,
            SetBedPID,
            UserThermistorParameters,
            DeployProbe = 401,
            StowProbe,
            BedLevelingState = 420,
            SetMeshValue,
            SaveSettings = 500,
            RestoreSettings,
            FactoryReset,
            ReportSettings,
            SetTMCSteppingMode = 569,
            SerialBaudRate = 575,
            FilamentChange = 600,
            LoadFilament = 701,
            UnloadFilament,
            XYZProbeOffset = 851,
            StepperMotorCurrent = 906,
        }
    }
}